### ISSUE TITLE
unknown flag:  --config Error

### ISSUE THREAD

**Issue by shiva4983** [katalon-studio/docker-images-samples#4]
Hi Team,

When I pass the proxy details using --config. I got unknown flag error. Kindly let me know how to fix it.

Thanks,
Siva

**Comment by devalex88** [comment]
Hi. Sorry for the late response. Could you please share the full log?

**Comment by shiva4983** [comment]
Hi,
Since I am running using Windows command prompt, the bash window closes immediately. Couldn't paste the log. my run_firefox.sh is having

#!/usr/bin/env bash

set -xe

current_dir=$(pwd)
project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
reports_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )/reports/firefox"

rm -rfv "$reports_dir"
mkdir -p "$reports_dir"

katalon_opts='-browserType="Firefox" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Admin - WorkFlow Sprints"'
docker run --rm -v "/$project_dir":/katalon/katalon/source:ro -v "/$reports_dir":/katalon/katalon/report -e KATALON_OPTS="$katalon_opts" --config -proxy.option="MANUAL_CONFIG" -proxy.server.type="HTTP" -proxy.server.address=http://myproxy.net -proxy.server.port=8080 -proxy.username=myProxyUserName -proxy.password=myProxyPassword katalonstudio/katalon

cd $current_dir

When I run from Command Prompt. Bash window open and try to run the docker command and finally shows 
unknown flag: --config
See 'docker run --help'

**Comment by shiva4983** [comment]
Hi,
Any update??

**Comment by shiva4983** [comment]
@devalex88 Any update?

**Comment by jejey** [comment]
hello, why don't you use docker quick start terminal ? Have you tried using it ? ( with boot2docker included)

**Comment by devalex88** [comment]
@shiva4983,

I'm sorry for the late response. The script should be

````
katalon_opts='-browserType="Firefox" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Admin - WorkFlow Sprints" --config -proxy.option="MANUAL_CONFIG" -proxy.server.type="HTTP" -proxy.server.address=http://myproxy.net -proxy.server.port=8080 -proxy.username=myProxyUserName -proxy.password=myProxyPassword'
docker run --rm -v "/$project_dir":/katalon/katalon/source:ro -v "/$reports_dir":/katalon/katalon/report -e KATALON_OPTS="$katalon_opts" katalonstudio/katalon
````

I realize that this is a bug in our README. It has been corrected.

**Comment by shiva4983** [comment]
Thanks @devalex88.
