### ISSUE TITLE
run katalon in docker windows 10 - beginner

### ISSUE THREAD

**Issue by MichalUrban999** [katalon-studio/docker-images-samples#6]
Hi guys, I try to run in the catalon test suite collection in windows 10 in docker, but I do not know the syntax structure. Would anyone be willing to help me run the test in the docker?

Here is we generate commnad from katalon:
katalon -noSplash -runMode = console -projectPath = "C: \ Users \ murban \ Katalon Studio \ AutomatTestCRM \ AutomatTestCRM_new.prj" -retry = 0 -testSuiteCollectionPath = "Test Suites / TestSuiteCollectionParallel / ParallelTest"

I have created in project folder: run_chrome.sh. What do I have to write into him?

I tried this, but it did not work :

docker run --rm -v //c/Users/murban/Katalon Studio\AutomatTestCRM/katalon:/katalon/katalon/source:ro -v /c/Users/murban/Katalon Studio\AutomatTestCRM/reports/chrome:/katalon/katalon/report -e 'KATALON_OPTS=-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TestSuiteCollectionParallel/ParallelTest"' katalonstudio/katalon

Thank you very much for your help.

**Comment by jejey** [comment]
have you watched and followed the steps in the video : https://www.katalon.com/videos/katalon-run-docker-container/ ?
That might help you

**Comment by devalex88** [comment]
Sorry for the inconvenience, @MichalUrban999. May I take a look at your console log?

**Comment by MichalUrban999** [comment]
Hi @jejey and @devalex88 i Watch video, this video is for Linux. I need to run in windows, there is different command.
@devalex88, please where i take a look to console log? After command "run_chrome.sh" in command line is nothnig. I try to look to event viewer, there is nothing too.

**Comment by MichalUrban999** [comment]
C:\Users\murban\Katalon Studio\AutomatTestCRM>docker run --rm -v //c/Users/murban/Katalon Studio\AutomatTestCRM/katalon:/katalon/katalon/source:ro -v /c/Users/murban/Katalon Studio\AutomatTestCRM/reports/chrome:/katalon/katalon/report -e 'KATALON_OPTS=-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TestSuiteCollectionParallel/ParallelTest"' katalonstudio/katalon
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by MichalUrban999** [comment]
Hi guyes the problem was in the folders where I had a space, then in the reverse slashes, now I can run but something does not seem to him yet

there is a console log:

C:\Users\murban\KatalonStudio\AutomatTestCRM>run_chrome.bat

C:\Users\murban\KatalonStudio\AutomatTestCRM>docker run --rm -v //c/users/murban/katalonstudio/automattestcrm/katalon:/katalon/katalon/source:ro -v /c/users/murban/katalonstudio/automattestcrm/reports/chrome:/katalon/katalon/report -e katalon_opts="-browsertype="chrome" -retry=0 -statusdelay=15 -testsuitecollectionpath="testsuites/testsuitecollectionparallel/paralleltest"" katalonstudio/katalon
Google Chrome 66.0.3359.139
Mozilla Firefox 59.0.2
Katalon Studio 5.4.1
+ echo 'Starting Katalon Studio'
Starting Katalon Studio
++ pwd
+ current_dir=/
+ tmp_dir=/katalon/katalon/tmp
+ mkdir -p /katalon/katalon/tmp
+ chmod -R 777 /katalon/katalon/tmp
+ project_dir=/katalon/katalon/project
+ mkdir -p /katalon/katalon/project
+ cp -r /katalon/katalon/source/. /katalon/katalon/project
+ touch /katalon/katalon/project/.classpath
+ chmod -R 777 /katalon/katalon/project
+ report_dir=/katalon/katalon/report
+ mkdir -p /katalon/katalon/report
+ chmod -R 777 /katalon/katalon/report
++ find /katalon/katalon/project -maxdepth 1 -type f -name '*.prj'
+ project_file=
+ cmd='/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath= '
+ /katalon/base/scripts/xvfb.sh start
+ XVFB=/usr/bin/Xvfb
+ XVFBARGS=':99 -screen 0 1024x768x24 -fbdir /var/run -ac'
+ PIDFILE=/var/run/xvfb.pid
+ case "$1" in
+ echo -n 'Starting virtual X frame buffer :99 1024x768x24'
Starting virtual X frame buffer :99 1024x768x24+ start-stop-daemon --start --quiet --pidfile /var/run/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -fbdir /var/run -ac
+ echo .
.
+ exit 0
+ cd /katalon/katalon/tmp
+ eval '/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath= '
++ /opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath=
joptsimple.OptionMissingRequiredArgumentException: Option projectPath requires an argument
        at joptsimple.RequiredArgumentOptionSpec.detectOptionArgument(RequiredArgumentOptionSpec.java:48)
        at joptsimple.ArgumentAcceptingOptionSpec.handleOption(ArgumentAcceptingOptionSpec.java:257)
        at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:520)
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59)
        at joptsimple.OptionParser.parse(OptionParser.java:396)
        at com.kms.katalon.execution.console.ConsoleMain.launch(ConsoleMain.java:70)
        at com.kms.katalon.console.application.Application.runConsole(Application.java:69)
        at com.kms.katalon.core.application.Application.runConsole(Application.java:72)
        at com.kms.katalon.core.application.Application.start(Application.java:56)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by devalex88** [comment]
Try docker run --rm -v //c/users/murban/katalonstudio/automattestcrm/katalon:/katalon/katalon/source:ro -v /c/users/murban/katalonstudio/automattestcrm/reports/chrome:/katalon/katalon/report -e KATALON_OPTS='-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath="Test Suites/TestSuiteCollectionParallel/ParallelTest"' katalonstudio/katalon

You can use spaces in folder paths as long as they are put inside double quotes.

**Comment by MichalUrban999** [comment]
I try to set the projectpath, but dont succeed:

C:\Users\murban\KatalonStudio\AutomatTestCRM>docker run --rm -v /c/users/murban/katalonstudio/automattestcrm/katalon:/katalon/katalon/source:ro -v /c/users/murban/katalonstudio/automattestcrm/reports/chrome:/katalon/katalon/report -p /c/users/murban/katalonstudio/automattestcrm:/katalon/katalon/automattestcrm_new.prj -e katalon_opts="-browsertype="chrome" -retry=0 -statusdelay=15 -testsuitecollectionpath="testsuites/testsuitecollectionparallel/paralleltest"" katalonstudio/katalon
docker: No port specified: /c/users/murban/katalonstudio/automattestcrm:/katalon/katalon/automattestcrm_new.prj<empty>.
See 'docker run --help'.

I followed these instructions:

https://github.com/minhhoangvn/katalon-docker
Execute test suite with katalon-container: docker run --rm --name test -v /Users/minhhoang/Workspace/WorkSpace/Docker/TestSample/:/KatalonTest/ -e p="/KatalonTest/TestSample.prj" -e s="Test\ Suites/GUI" -e b=Chrome -it katalon-container
Link your project folder from host machine to docker container via -v /Users/minhhoang/Workspace/WorkSpace/Docker/TestSample/:/KatalonTest/
Set container environment variable in sample command above
List of args belows:
-p -- project path value
-s -- test suite path value
-r -- report path value
-b -- browser type value, default is firefox browser
-v -- enable console log mode in kataon

**Comment by MichalUrban999** [comment]
Hi, do you know why my docker does not want to take the "Test Suite"?

there is command what i want to run:
docker run --rm -e KATALON_OPTS="-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath=""test suites/testsuitecollectionparallel/paralleltest""" -v /c/users/murban/katalonstudio/automattestcrm:/katalon/katalon/source:ro -v /c/users/murban/katalonstudio/automattestcrm/reports:/katalon/katalon/report katalonstudio/katalon

there is result from command line:
docker : Unable to find image 'suites/testsuitecollectionparallel/paralleltest:latest' locally
At line:1 char:1
+ docker run --rm -e KATALON_OPTS="-browserType="Chrome" -retry=0 -stat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find ...latest' locally:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded whi
le awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

When I try to remove a space in the "Test Suite" path to "TestSuite" the docker gets farther, but then it fades into error:

Google Chrome 67.0.3396.62 
Mozilla Firefox 60.0.1
Katalon Studio 5.4.2
Starting Katalon Studio
docker : + echo 'Starting Katalon Studio'
At line:1 char:1
+ docker run --rm -e KATALON_OPTS="-browserType="Chrome" -retry=0 -stat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (+ echo 'Starting Katalon Studio':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
++ pwd
+ current_dir=/
+ tmp_dir=/katalon/katalon/tmp
+ mkdir -p /katalon/katalon/tmp
+ chmod -R 777 /katalon/katalon/tmp
+ project_dir=/katalon/katalon/project
+ mkdir -p /katalon/katalon/project
+ cp -r /katalon/katalon/source/. /katalon/katalon/project
+ touch /katalon/katalon/project/.classpath
+ chmod -R 777 /katalon/katalon/project
+ report_dir=/katalon/katalon/report
+ mkdir -p /katalon/katalon/report
+ chmod -R 777 /katalon/katalon/report
++ find /katalon/katalon/project -maxdepth 1 -type f -name '*.prj'
+ project_file=/katalon/katalon/project/AutomatTestCRM_new.prj
+ cmd='/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath=/katalon/katalon/project/AutomatTestCRM_new.prj -browserType=Chrome -retry=0 -statusDelay=15 -testSuiteCo
llectionPath=testsuites/testsuitecollectionparallel/paralleltest'
+ /katalon/base/scripts/xvfb.sh start
+ XVFB=/usr/bin/Xvfb
+ XVFBARGS=':99 -screen 0 1024x768x24 -fbdir /var/run -ac'
+ PIDFILE=/var/run/xvfb.pid
+ case "$1" in
+ echo -n 'Starting virtual X frame buffer :99 1024x768x24'
+ start-stop-daemon --start --quiet --pidfile /var/run/xvfb.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -fbdir /var/run -ac
Starting virtual X frame buffer :99 1024x768x24.
+ echo .
+ exit 0
+ cd /katalon/katalon/tmp
+ eval '/opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath=/katalon/katalon/project/AutomatTestCRM_new.prj -browserType=Chrome -retry=0 -statusDelay=15 -testSuiteC
ollectionPath=testsuites/testsuitecollectionparallel/paralleltest'
++ /opt/katalonstudio/katalon -runMode=console -reportFolder=/katalon/katalon/report -projectPath=/katalon/katalon/project/AutomatTestCRM_new.prj -browserType=Chrome -retry=0 -statusDelay=15 -testSuiteCollec
tionPath=testsuites/testsuitecollectionparallel/paralleltest
Starting Groovy-Eclipse compiler resolver.  Specified compiler level: unspecified
133 2.4.7.xx-201611170128-e46 = ACTIVE
Test suite 'testsuites/testsuitecollectionparallel/paralleltest' not found.

**Have you please any tips to fix this?**

**Comment by MichalUrban999** [comment]
Hi guys, I managed to run catalon in the docker, the final command is:

docker run --rm -e KATALON_OPTS="-browserType="Chrome" -retry=0 -statusDelay=15 -testSuiteCollectionPath=Test\ Suites/TestSuiteCollectionParallel/ParallelTest" -v/c/users/murban/katalonstudio/automattestcrm:/katalon/katalon/source:ro -v /c/users/murban/katalonstudio/automattestcrm/reports:/katalon/katalon/report katalonstudio/katalon

Thank you all for your help, perhaps it will help someone.

**Comment by nadim1975** [comment]
@MichalUrban999 
Hi Michal , I have similar issue and following your steps in changing Katalon docker command

`docker run --rm -e KATALON_OPTS="-browserType="Chrome" -executionProfile="QA" -retry=0 -statusDelay=15 -testSuitePath=Test\ Suites/UI/Regression" -v/c/Users/nhussein/"Katalon Studio"/GPORTAL:/katalon/katalon/source:ro -v /c/Users/nhussein/"Katalon Studio"/GPORTAL/reports:/katalon/katalon/report katalonstudio/katalon
`
When I run the command I get below output in Docker and no log is showing ... can you plz help

+ cat /katalon/version
Google Chrome 71.0.3578.98
Mozilla Firefox 64.0
Katalon Studio 5.10.1
Thank you for using Katalon Studio. Please visit https://github.com/katalon-studio/docker-images for usage.
+ echo 'Thank you for using Katalon Studio. Please visit https://github.com/katalon-studio/docker-images for usage.'
